import { get, post, put, del, postChat, getDown } from "../../utils/request";



export async function createSessions(data = {}) {
  return post("/api/v1/sessions", data);
}

export async function getSessionsList(page: number, page_size: number, source?: string) {
  const params = new URLSearchParams({ page: String(page), pageSize: String(page_size) });
  if (source) {
    params.set("source", source);
  }
  return get(`/api/v1/sessions?${params.toString()}`);
}

export async function pinSession(sessionId: string) {
  return post(`/api/v1/sessions/${sessionId}/pin`, {});
}

export async function unpinSession(sessionId: string) {
  return del(`/api/v1/sessions/${sessionId}/pin`);
}

export async function generateSessionsTitle(sessionId: string, data: any) {
  return post(`/api/v1/sessions/${sessionId}/generate_title`, data);
}

export async function updateSession(sessionId: string, data: { title: string; description?: string }) {
  return put(`/api/v1/sessions/${sessionId}`, data);
}

export async function knowledgeChat(data: { sessionId: string; query: string; }) {
  return postChat(`/api/v1/knowledge-chat/${data.sessionId}`, { query: data.query, channel: "web" });
}

// Agent chat with streaming support
export async function agentChat(data: { 
  sessionId: string; 
  query: string;
  knowledgeBaseIds?: string[];
  agentEnabled: boolean;
}) {
  return postChat(`/api/v1/agent-chat/${data.sessionId}`, { 
    query: data.query,
    knowledgeBaseIds: data.knowledgeBaseIds,
    agentEnabled: data.agentEnabled,
    channel: "web"
  });
}

export async function getMessageList(data: { sessionId: string; limit: number, created_at: string }) {
  // 查询参数是 §14.9l S2 后的 camelCase（beforeTime）；data.created_at 只是本地游标
  // （上一页最早一条消息的 createdAt），不是线格式键。
  if (data.created_at) {
    return get(`/api/v1/messages/${data.sessionId}/load?beforeTime=${encodeURIComponent(data.created_at)}&limit=${data.limit}`);
  } else {
    return get(`/api/v1/messages/${data.sessionId}/load?limit=${data.limit}`);
  }
}

export async function delSession(sessionId: string) {
  return del(`/api/v1/sessions/${sessionId}`);
}

export async function batchDelSessions(ids: string[]) {
  return del(`/api/v1/sessions/batch`, { ids });
}

export async function deleteAllSessions() {
  return del(`/api/v1/sessions/batch`, { deleteAll: true });
}

export async function getSession(sessionId: string) {
  return get(`/api/v1/sessions/${sessionId}`);
}

export async function stopSession(sessionId: string, messageId: string) {
  return post(`/api/v1/sessions/${sessionId}/stop`, { messageId: messageId });
}

export async function clearSessionMessages(sessionId: string) {
  return del(`/api/v1/sessions/${sessionId}/messages`);
}

// ---------------------------------------------------------------------------
// Skill artifacts (files generated by skill scripts during agent turns)
//
// The backend keeps the physical storage path private and indexes each file by
// its position (:index) in the owning assistant message. The list endpoints
// return metadata only — clients must go through downloadArtifact to fetch
// the actual bytes so ownership checks always run server-side.
// ---------------------------------------------------------------------------

export interface ArtifactMeta {
  index: number;
  /**
   * `resource://<handle>` — the artifact's stable identity, and the destination
   * the answer body references. Empty when the deployment runs without a
   * resource catalog, in which case the body references files by name.
   */
  handle?: string | null;
  // 键名＝服务端字段名（§14.9l S2 后为 camelCase）：产物列表端点（ArtifactView）与
  // 消息面 jsonb（messages.artifacts 里的 MessageArtifact）两处形状一致。
  fileName: string;
  fileType: string;
  fileSize: number;
  sourcePath: string;
  modTime: string;
  createdAt: string;
  /** 消息面 jsonb 里的存储引用（`resource://<handle>`）；ArtifactView 用 `handle` 表达。 */
  url?: string;
}

// listMessageArtifacts returns the artifacts attached to a single assistant
// message. Used by the drawer opened from the message action toolbar.
export async function listMessageArtifacts(sessionId: string, messageId: string) {
  return get(
    `/api/v1/sessions/${sessionId}/messages/${messageId}/artifacts`,
  );
}

// listSessionArtifacts returns every artifact recorded against the whole
// session, in creation order. Powers "download everything generated in this
// chat" drawers.
export async function listSessionArtifacts(sessionId: string) {
  return get(`/api/v1/sessions/${sessionId}/artifacts`);
}

// downloadArtifact streams a single artifact's bytes as a Blob so the caller
// can trigger a browser download. A plain `<a href>` cannot be used because
// axios attaches the Bearer token per request; issuing the download via
// `getDown` keeps auth intact and lets the response be turned into an
// object URL.
export async function downloadArtifact(
  sessionId: string,
  messageId: string,
  index: number,
): Promise<Blob> {
  return getDown(
    `/api/v1/sessions/${sessionId}/messages/${messageId}/artifacts/${index}/download`,
  );
}
