package com.ragagent;

import org.springframework.jdbc.core.JdbcTemplate;

/**
 * 契约测试共享的 H2 schema（阶段 1+2 并集）。
 *
 * 所有契约测试必须用同一份 DDL：H2 内存库在 JVM 生命周期内共享
 * （DB_CLOSE_DELAY=-1），CREATE TABLE IF NOT EXISTS 不会补列，
 * 表结构以第一个执行的测试类为准——分叉的 DDL 会让后跑的类炸列错误。
 * 新增模块时在此追加表定义，禁止在测试类里私建同名表。
 */
public final class TestSchema {

    private TestSchema() {}

    public static void createTables(JdbcTemplate jdbc) {
        jdbc.execute("CREATE TABLE IF NOT EXISTS users (" +
                "id VARCHAR(36) PRIMARY KEY, username VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL," +
                "password_hash VARCHAR(255) NOT NULL, avatar VARCHAR(500), tenant_id BIGINT," +
                "is_active BOOLEAN NOT NULL DEFAULT TRUE, can_access_all_tenants BOOLEAN NOT NULL DEFAULT FALSE," +
                "is_system_admin BOOLEAN NOT NULL DEFAULT FALSE, preferences VARCHAR NOT NULL DEFAULT '{}'," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS tenants (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "name VARCHAR NOT NULL, description VARCHAR NOT NULL DEFAULT '', status VARCHAR NOT NULL DEFAULT 'active'," +
                "retriever_engines VARCHAR NOT NULL DEFAULT '[]', business VARCHAR NOT NULL DEFAULT ''," +
                "storage_quota BIGINT NOT NULL DEFAULT 10737418240, storage_used BIGINT NOT NULL DEFAULT 0," +
                "context_config VARCHAR, web_search_config VARCHAR, parser_engine_config VARCHAR, credentials VARCHAR," +
                "storage_engine_config VARCHAR, default_storage_backend_id VARCHAR(36)," +
                "chat_history_config VARCHAR, retrieval_config VARCHAR, memory_config VARCHAR," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS tenant_members (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "user_id VARCHAR(36) NOT NULL, tenant_id BIGINT NOT NULL," +
                "role VARCHAR(20) NOT NULL DEFAULT 'contributor', status VARCHAR(20) NOT NULL DEFAULT 'active'," +
                "invited_by VARCHAR(36), joined_at TIMESTAMP WITH TIME ZONE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS auth_tokens (" +
                "id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL, token TEXT NOT NULL," +
                "token_type VARCHAR(50) NOT NULL, expires_at TIMESTAMP WITH TIME ZONE NOT NULL," +
                "is_revoked BOOLEAN NOT NULL DEFAULT FALSE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS models (" +
                "id VARCHAR(64) PRIMARY KEY, tenant_id BIGINT NOT NULL, name VARCHAR(255) NOT NULL," +
                "display_name VARCHAR(255) NOT NULL DEFAULT '', type VARCHAR(50) NOT NULL, source VARCHAR(50) NOT NULL," +
                "description TEXT, parameters VARCHAR NOT NULL, is_default BOOLEAN NOT NULL DEFAULT FALSE," +
                "is_builtin BOOLEAN NOT NULL DEFAULT FALSE, managed_by VARCHAR(32) NOT NULL DEFAULT ''," +
                "status VARCHAR(50) NOT NULL DEFAULT 'active'," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        // knowledge_bases：阶段 2 usage 查询 + 阶段 3 CRUD 共用的**全列**定义
        //（H2 共享 JVM，CREATE IF NOT EXISTS 以先建者为准——禁止在别处再建此表）
        jdbc.execute("CREATE TABLE IF NOT EXISTS knowledge_bases (" +
                "id VARCHAR(36) PRIMARY KEY, name VARCHAR NOT NULL, tenant_id BIGINT NOT NULL," +
                "embedding_model_id VARCHAR(64), summary_model_id VARCHAR(64)," +
                "image_processing_config VARCHAR, vlm_config VARCHAR, asr_config VARCHAR, wiki_config VARCHAR," +
                "type VARCHAR(32) NOT NULL DEFAULT 'document'," +
                "is_temporary BOOLEAN NOT NULL DEFAULT FALSE, description TEXT, creator_id VARCHAR(36)," +
                "chunking_config VARCHAR NOT NULL DEFAULT '{}'," +
                "storage_provider_config VARCHAR, storage_backend_id VARCHAR(36)," +
                "cos_config VARCHAR NOT NULL DEFAULT '{}', vector_store_id VARCHAR(36)," +
                "extract_config VARCHAR, faq_config VARCHAR," +
                "question_generation_config VARCHAR, auto_tag_config VARCHAR," +
                "indexing_strategy VARCHAR, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS custom_agents (" +
                "id VARCHAR(36) PRIMARY KEY, name VARCHAR NOT NULL, tenant_id BIGINT NOT NULL," +
                "config VARCHAR, deleted_at TIMESTAMP WITH TIME ZONE)");
        // ── 阶段 3：知识库 ──
        jdbc.execute("CREATE TABLE IF NOT EXISTS storage_backends (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL, name VARCHAR NOT NULL," +
                "provider VARCHAR(32) NOT NULL, config VARCHAR NOT NULL DEFAULT '{}'," +
                "source VARCHAR(16) NOT NULL DEFAULT 'user', status VARCHAR(16) NOT NULL DEFAULT 'active'," +
                "legacy_alias BOOLEAN NOT NULL DEFAULT FALSE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS knowledges (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL, knowledge_base_id VARCHAR NOT NULL," +
                "type VARCHAR(50) NOT NULL, title VARCHAR NOT NULL, description TEXT, source VARCHAR NOT NULL," +
                "channel VARCHAR(50) NOT NULL DEFAULT 'web', parse_status VARCHAR(50) NOT NULL DEFAULT 'pending'," +
                "pending_subtasks_count INTEGER NOT NULL DEFAULT 0, summary_status VARCHAR(32) NOT NULL DEFAULT 'none'," +
                "enable_status VARCHAR(50) NOT NULL DEFAULT 'enabled'," +
                "embedding_model_id VARCHAR(64), file_name VARCHAR, folder_path VARCHAR NOT NULL DEFAULT ''," +
                "file_type VARCHAR, file_size BIGINT, file_hash VARCHAR, file_path TEXT," +
                "storage_size BIGINT NOT NULL DEFAULT 0, metadata VARCHAR, custom_metadata VARCHAR," +
                "last_faq_import_result VARCHAR," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "processed_at TIMESTAMP WITH TIME ZONE, error_message TEXT," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS chunks (" +
                "id VARCHAR(36) PRIMARY KEY, seq_id BIGINT, tenant_id BIGINT NOT NULL," +
                "knowledge_id VARCHAR NOT NULL, knowledge_base_id VARCHAR NOT NULL, tag_id VARCHAR," +
                "content TEXT NOT NULL, source_content TEXT, content_revision INTEGER NOT NULL DEFAULT 0," +
                "index_status VARCHAR(16) NOT NULL DEFAULT 'ready', last_editor_id VARCHAR(64)," +
                "chunk_index INTEGER NOT NULL, is_enabled BOOLEAN NOT NULL DEFAULT TRUE," +
                "flags INTEGER NOT NULL DEFAULT 1, status INTEGER NOT NULL DEFAULT 0," +
                "start_at INTEGER NOT NULL, end_at INTEGER NOT NULL," +
                "pre_chunk_id VARCHAR, next_chunk_id VARCHAR, chunk_type VARCHAR(20) NOT NULL DEFAULT 'text'," +
                "parent_chunk_id VARCHAR, relation_chunks VARCHAR, indirect_relation_chunks VARCHAR," +
                "metadata VARCHAR, content_hash VARCHAR, image_info TEXT, context_header TEXT," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS user_kb_pins (" +
                "user_id VARCHAR(36) NOT NULL, knowledge_base_id VARCHAR(36) NOT NULL," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS embeddings (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "source_id VARCHAR(64) NOT NULL, source_type INTEGER NOT NULL," +
                "chunk_id VARCHAR(64), knowledge_id VARCHAR(64), knowledge_base_id VARCHAR(64)," +
                "content TEXT, dimension INTEGER NOT NULL, embedding VARCHAR," +
                "CONSTRAINT embeddings_unique_source UNIQUE (source_id, source_type))");
        // ── 阶段 4.1：MCP（列名/约束以 Go 迁移 000001/000042/000062/000064/000074/000091/000092 为准） ──
        jdbc.execute("CREATE TABLE IF NOT EXISTS mcp_services (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL, name VARCHAR(255) NOT NULL," +
                "description TEXT, enabled BOOLEAN NOT NULL DEFAULT TRUE," +
                "transport_type VARCHAR(50) NOT NULL, url VARCHAR(512)," +
                "headers VARCHAR, auth_config VARCHAR, advanced_config VARCHAR," +
                "stdio_config VARCHAR, env_vars VARCHAR," +
                "is_builtin BOOLEAN NOT NULL DEFAULT FALSE," +
                "usage_instructions TEXT NOT NULL DEFAULT ''," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS mcp_oauth_clients (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL," +
                "service_id VARCHAR(36) NOT NULL, client_id VARCHAR(512) NOT NULL," +
                "client_secret TEXT, redirect_uri VARCHAR(1024)," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "CONSTRAINT mcp_oauth_clients_tenant_svc UNIQUE (tenant_id, service_id))");
        // user_id 放宽到 VARCHAR(512)、principal_type/principal_id 为 struct 演进后的形态
        // （迁移 000064 补列；以 Go struct 为准）
        jdbc.execute("CREATE TABLE IF NOT EXISTS mcp_oauth_tokens (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL," +
                "user_id VARCHAR(512) NOT NULL, principal_type VARCHAR(32) NOT NULL," +
                "principal_id VARCHAR(512) NOT NULL, service_id VARCHAR(36) NOT NULL," +
                "access_token TEXT, refresh_token TEXT, token_type VARCHAR(32)," +
                "expires_at TIMESTAMP WITH TIME ZONE," +
                "refresh_lease_id VARCHAR(36), refresh_lease_until TIMESTAMP WITH TIME ZONE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "CONSTRAINT mcp_oauth_tokens_tenant_principal_svc " +
                "UNIQUE (tenant_id, principal_type, principal_id, service_id))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS mcp_metadata (" +
                "tenant_id BIGINT NOT NULL, service_id VARCHAR(36) NOT NULL," +
                "principal VARCHAR(255) NOT NULL DEFAULT ''," +
                "config_fingerprint VARCHAR(64) NOT NULL, tools VARCHAR NOT NULL," +
                "instructions TEXT NOT NULL DEFAULT '', server_name TEXT NOT NULL DEFAULT ''," +
                "server_version TEXT NOT NULL DEFAULT '', server_description TEXT NOT NULL DEFAULT ''," +
                "synced_at TIMESTAMP WITH TIME ZONE NOT NULL," +
                "PRIMARY KEY (tenant_id, service_id, principal))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS mcp_tool_approvals (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL," +
                "service_id VARCHAR(36) NOT NULL, tool_name VARCHAR(512) NOT NULL," +
                "require_approval BOOLEAN NOT NULL DEFAULT FALSE," +
                "enabled BOOLEAN NOT NULL DEFAULT TRUE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "CONSTRAINT mcp_tool_approvals_tenant_svc_tool UNIQUE (tenant_id, service_id, tool_name))");
        // mcp_metadata 的工具计数走 jsonb_array_length（PG 方言）；H2 没有这个函数，
        // 这里注册同名 ALIAS 指向本类的 Java 实现，让**同一条 SQL** 在测试库上也能跑。
        jdbc.execute("CREATE ALIAS IF NOT EXISTS json_array_length FOR "
                + "\"com.ragagent.TestSchema.jsonArrayLength\"");
    }

    /**
     * H2 ALIAS 目标：对照 PG {@code json_array_length(json)}。
     * 入参是 H2 的 VARCHAR（测试库用 VARCHAR 承载 jsonb），内容必须是 JSON 数组。
     */
    public static int jsonArrayLength(String json) {
        if (json == null || json.isEmpty()) {
            return 0;
        }
        try {
            com.fasterxml.jackson.databind.JsonNode node =
                    new com.fasterxml.jackson.databind.ObjectMapper().readTree(json);
            return node.isArray() ? node.size() : 0;
        } catch (Exception e) {
            throw new IllegalArgumentException("json_array_length: invalid JSON", e);
        }
    }

    /** 清空全部数据（外键无依赖，任意顺序） */
    public static void resetData(JdbcTemplate jdbc) {
        jdbc.execute("DELETE FROM auth_tokens");
        jdbc.execute("DELETE FROM tenant_members");
        jdbc.execute("DELETE FROM users");
        jdbc.execute("DELETE FROM tenants");
        jdbc.execute("DELETE FROM models");
        jdbc.execute("DELETE FROM knowledge_bases");
        jdbc.execute("DELETE FROM knowledges");
        jdbc.execute("DELETE FROM chunks");
        jdbc.execute("DELETE FROM user_kb_pins");
        jdbc.execute("DELETE FROM storage_backends");
        jdbc.execute("DELETE FROM embeddings");
        jdbc.execute("DELETE FROM custom_agents");
        jdbc.execute("DELETE FROM mcp_tool_approvals");
        jdbc.execute("DELETE FROM mcp_metadata");
        jdbc.execute("DELETE FROM mcp_oauth_tokens");
        jdbc.execute("DELETE FROM mcp_oauth_clients");
        jdbc.execute("DELETE FROM mcp_services");
    }
}
