package com.ragagent;

import org.springframework.jdbc.core.JdbcTemplate;

/**
 * 契约测试共享的 H2 schema。
 *
 * 所有契约测试必须用同一份 DDL：H2 内存库在 JVM 生命周期内共享
 * （DB_CLOSE_DELAY=-1），CREATE TABLE IF NOT EXISTS 不会补列，
 * 表结构以第一个执行的测试类为准——分叉的 DDL 会让后跑的类炸列错误。
 * 新增模块时在此追加表定义，禁止在测试类里私建同名表。
 */
public final class TestSchema {

    private TestSchema() {}

    public static void createTables(JdbcTemplate jdbc) {
        jdbc.execute("CREATE TABLE IF NOT EXISTS users (" +
                "id VARCHAR(36) PRIMARY KEY, username VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL," +
                "password_hash VARCHAR(255) NOT NULL, avatar VARCHAR(500), tenant_id BIGINT," +
                "is_active BOOLEAN NOT NULL DEFAULT TRUE, can_access_all_tenants BOOLEAN NOT NULL DEFAULT FALSE," +
                "is_system_admin BOOLEAN NOT NULL DEFAULT FALSE, preferences VARCHAR NOT NULL DEFAULT '{}'," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS tenants (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "name VARCHAR NOT NULL, description VARCHAR NOT NULL DEFAULT '', status VARCHAR NOT NULL DEFAULT 'active'," +
                "retriever_engines VARCHAR NOT NULL DEFAULT '[]', business VARCHAR NOT NULL DEFAULT ''," +
                "storage_quota BIGINT NOT NULL DEFAULT 10737418240, storage_used BIGINT NOT NULL DEFAULT 0," +
                "context_config VARCHAR, web_search_config VARCHAR, parser_engine_config VARCHAR, credentials VARCHAR," +
                "storage_engine_config VARCHAR, default_storage_backend_id VARCHAR(36)," +
                "chat_history_config VARCHAR, retrieval_config VARCHAR, memory_config VARCHAR," +
                "api_principal_config VARCHAR," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        // 迁移 000048 + 000064（token/accepted_count）：pending 邀请的状态机
        jdbc.execute("CREATE TABLE IF NOT EXISTS tenant_invitations (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "invitee_user_id VARCHAR(36) NOT NULL DEFAULT ''," +
                "invited_by VARCHAR(36), role VARCHAR(20) NOT NULL," +
                "status VARCHAR(20) NOT NULL DEFAULT 'pending', message VARCHAR(500)," +
                "expires_at TIMESTAMP WITH TIME ZONE NOT NULL, responded_at TIMESTAMP WITH TIME ZONE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE," +
                "token VARCHAR(64) NOT NULL DEFAULT '', accepted_count INTEGER NOT NULL DEFAULT 0)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS tenant_members (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "user_id VARCHAR(36) NOT NULL, tenant_id BIGINT NOT NULL," +
                "role VARCHAR(20) NOT NULL DEFAULT 'contributor', status VARCHAR(20) NOT NULL DEFAULT 'active'," +
                "invited_by VARCHAR(36), joined_at TIMESTAMP WITH TIME ZONE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS auth_tokens (" +
                "id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL, token TEXT NOT NULL," +
                "token_type VARCHAR(50) NOT NULL, expires_at TIMESTAMP WITH TIME ZONE NOT NULL," +
                "is_revoked BOOLEAN NOT NULL DEFAULT FALSE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS models (" +
                "id VARCHAR(64) PRIMARY KEY, tenant_id BIGINT NOT NULL, name VARCHAR(255) NOT NULL," +
                "display_name VARCHAR(255) NOT NULL DEFAULT '', type VARCHAR(50) NOT NULL, source VARCHAR(50) NOT NULL," +
                "description TEXT, parameters VARCHAR NOT NULL, is_default BOOLEAN NOT NULL DEFAULT FALSE," +
                "is_builtin BOOLEAN NOT NULL DEFAULT FALSE, managed_by VARCHAR(32) NOT NULL DEFAULT ''," +
                "status VARCHAR(50) NOT NULL DEFAULT 'active'," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        // knowledge_bases：usage 查询与 CRUD 共用的**全列**定义
        //（H2 共享 JVM，CREATE IF NOT EXISTS 以先建者为准——禁止在别处再建此表）
        jdbc.execute("CREATE TABLE IF NOT EXISTS knowledge_bases (" +
                "id VARCHAR(36) PRIMARY KEY, name VARCHAR NOT NULL, tenant_id BIGINT NOT NULL," +
                "embedding_model_id VARCHAR(64), summary_model_id VARCHAR(64)," +
                "image_processing_config VARCHAR, vlm_config VARCHAR, asr_config VARCHAR, wiki_config VARCHAR," +
                "type VARCHAR(32) NOT NULL DEFAULT 'document'," +
                "is_temporary BOOLEAN NOT NULL DEFAULT FALSE, description TEXT, creator_id VARCHAR(36)," +
                "chunking_config VARCHAR NOT NULL DEFAULT '{}'," +
                "storage_provider_config VARCHAR, storage_backend_id VARCHAR(36)," +
                "storage_config VARCHAR NOT NULL DEFAULT '{}', vector_store_id VARCHAR(36)," +
                "extract_config VARCHAR, faq_config VARCHAR," +
                "question_generation_config VARCHAR, auto_tag_config VARCHAR," +
                "indexing_strategy VARCHAR, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        // custom_agents：协作面全列定义——
        // 共享智能体响应要序列化 description/avatar/is_builtin/created_by/时间戳。
        jdbc.execute("CREATE TABLE IF NOT EXISTS custom_agents (" +
                "id VARCHAR(36) PRIMARY KEY, name VARCHAR(255) NOT NULL, description TEXT," +
                "avatar VARCHAR(64) DEFAULT '', is_builtin BOOLEAN NOT NULL DEFAULT FALSE," +
                "tenant_id BIGINT NOT NULL, created_by VARCHAR(36) DEFAULT ''," +
                "config VARCHAR, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        // ── 知识库 ──
        jdbc.execute("CREATE TABLE IF NOT EXISTS storage_backends (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL, name VARCHAR NOT NULL," +
                "provider VARCHAR(32) NOT NULL, config VARCHAR NOT NULL DEFAULT '{}'," +
                "source VARCHAR(16) NOT NULL DEFAULT 'user', status VARCHAR(16) NOT NULL DEFAULT 'active'," +
                "legacy_alias BOOLEAN NOT NULL DEFAULT FALSE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS knowledges (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL, knowledge_base_id VARCHAR NOT NULL," +
                "type VARCHAR(50) NOT NULL, title VARCHAR NOT NULL, description TEXT, source VARCHAR NOT NULL," +
                "channel VARCHAR(50) NOT NULL DEFAULT 'web', parse_status VARCHAR(50) NOT NULL DEFAULT 'pending'," +
                "pending_subtasks_count INTEGER NOT NULL DEFAULT 0, summary_status VARCHAR(32) NOT NULL DEFAULT 'none'," +
                "enable_status VARCHAR(50) NOT NULL DEFAULT 'enabled'," +
                "embedding_model_id VARCHAR(64), file_name VARCHAR, folder_path VARCHAR NOT NULL DEFAULT ''," +
                "file_type VARCHAR, file_size BIGINT, file_hash VARCHAR, file_path TEXT," +
                "storage_size BIGINT NOT NULL DEFAULT 0, metadata VARCHAR, custom_metadata VARCHAR," +
                "last_faq_import_result VARCHAR," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "processed_at TIMESTAMP WITH TIME ZONE, error_message TEXT," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS chunks (" +
                "id VARCHAR(36) PRIMARY KEY, seq_id BIGINT, tenant_id BIGINT NOT NULL," +
                "knowledge_id VARCHAR NOT NULL, knowledge_base_id VARCHAR NOT NULL, tag_id VARCHAR," +
                "content TEXT NOT NULL, source_content TEXT, content_revision INTEGER NOT NULL DEFAULT 0," +
                "index_status VARCHAR(16) NOT NULL DEFAULT 'ready', last_editor_id VARCHAR(64)," +
                "chunk_index INTEGER NOT NULL, is_enabled BOOLEAN NOT NULL DEFAULT TRUE," +
                "flags INTEGER NOT NULL DEFAULT 1, status INTEGER NOT NULL DEFAULT 0," +
                "start_at INTEGER NOT NULL, end_at INTEGER NOT NULL," +
                "pre_chunk_id VARCHAR, next_chunk_id VARCHAR, chunk_type VARCHAR(20) NOT NULL DEFAULT 'text'," +
                "parent_chunk_id VARCHAR, relation_chunks VARCHAR, indirect_relation_chunks VARCHAR," +
                "metadata VARCHAR, content_hash VARCHAR, image_info TEXT, context_header TEXT," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        // 迁移 000078（chunk 编辑与修订历史）
        jdbc.execute("CREATE TABLE IF NOT EXISTS chunk_revisions (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL," +
                "knowledge_base_id VARCHAR(36) NOT NULL, knowledge_id VARCHAR(36) NOT NULL," +
                "chunk_id VARCHAR(36) NOT NULL, revision INTEGER NOT NULL," +
                "content TEXT NOT NULL DEFAULT '', is_enabled BOOLEAN NOT NULL DEFAULT TRUE," +
                "editor_id VARCHAR(64) NOT NULL DEFAULT '', edit_source VARCHAR(16) NOT NULL DEFAULT 'user'," +
                "edited_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP," +
                "created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS user_kb_pins (" +
                "user_id VARCHAR(36) NOT NULL, knowledge_base_id VARCHAR(36) NOT NULL," +
                "pinned_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)");
        // ── knowledge_tags + knowledge_tag_relations（列序/类型以迁移
        // 000063 为准；seq_id 是迁移 000010 加的 NOT NULL 序列列，
        // H2 无序列 → 播种时显式给值） ──
        jdbc.execute("CREATE TABLE IF NOT EXISTS knowledge_tags (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL," +
                "knowledge_base_id VARCHAR(36) NOT NULL, name VARCHAR(128) NOT NULL," +
                "color VARCHAR(32), sort_order INTEGER NOT NULL DEFAULT 0," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE, seq_id BIGINT NOT NULL)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS knowledge_tag_relations (" +
                "knowledge_id VARCHAR(36) NOT NULL, tag_id VARCHAR(36) NOT NULL," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "PRIMARY KEY (knowledge_id, tag_id))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS embeddings (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "source_id VARCHAR(64) NOT NULL, source_type INTEGER NOT NULL," +
                "chunk_id VARCHAR(64), knowledge_id VARCHAR(64), knowledge_base_id VARCHAR(64)," +
                "tag_id VARCHAR(36)," +
                "content TEXT, dimension INTEGER NOT NULL, embedding VARCHAR," +
                "is_enabled BOOLEAN DEFAULT TRUE," +
                "CONSTRAINT embeddings_unique_source UNIQUE (source_id, source_type))");
        // knowledge_processing_spans（迁移 000055 + 000066）：jsonb → CLOB，
        // 唯一约束对齐 uq_kpspan_attempt_span（H2 分支的 upsert 走先查后写，不依赖它）
        jdbc.execute("CREATE TABLE IF NOT EXISTS knowledge_processing_spans (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "knowledge_id VARCHAR(64) NOT NULL," +
                "attempt INTEGER NOT NULL DEFAULT 1," +
                "span_id VARCHAR(64) NOT NULL," +
                "parent_span_id VARCHAR(64)," +
                "name VARCHAR(255) NOT NULL," +
                "kind VARCHAR(16) NOT NULL," +
                "status VARCHAR(16) NOT NULL," +
                "input CLOB, output CLOB, metadata CLOB," +
                "error_code VARCHAR(64), error_message CLOB, error_detail CLOB," +
                "started_at TIMESTAMP WITH TIME ZONE," +
                "finished_at TIMESTAMP WITH TIME ZONE," +
                "duration_ms BIGINT," +
                "created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP," +
                "CONSTRAINT uq_kpspan_attempt_span UNIQUE (knowledge_id, attempt, span_id))");
        // ── MCP（列名/约束以迁移 000001/000042/000062/000064/000074/000091/000092 为准） ──
        jdbc.execute("CREATE TABLE IF NOT EXISTS mcp_services (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL, name VARCHAR(255) NOT NULL," +
                "description TEXT, enabled BOOLEAN NOT NULL DEFAULT TRUE," +
                "transport_type VARCHAR(50) NOT NULL, url VARCHAR(512)," +
                "headers VARCHAR, auth_config VARCHAR, advanced_config VARCHAR," +
                "stdio_config VARCHAR, env_vars VARCHAR," +
                "is_builtin BOOLEAN NOT NULL DEFAULT FALSE," +
                "usage_instructions TEXT NOT NULL DEFAULT ''," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS mcp_oauth_clients (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL," +
                "service_id VARCHAR(36) NOT NULL, client_id VARCHAR(512) NOT NULL," +
                "client_secret TEXT, redirect_uri VARCHAR(1024)," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "CONSTRAINT mcp_oauth_clients_tenant_svc UNIQUE (tenant_id, service_id))");
        // user_id 放宽到 VARCHAR(512)、principal_type/principal_id 为实体演进后的形态
        // （迁移 000064 补列）
        jdbc.execute("CREATE TABLE IF NOT EXISTS mcp_oauth_tokens (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL," +
                "user_id VARCHAR(512) NOT NULL, principal_type VARCHAR(32) NOT NULL," +
                "principal_id VARCHAR(512) NOT NULL, service_id VARCHAR(36) NOT NULL," +
                "access_token TEXT, refresh_token TEXT, token_type VARCHAR(32)," +
                "expires_at TIMESTAMP WITH TIME ZONE," +
                "refresh_lease_id VARCHAR(36), refresh_lease_until TIMESTAMP WITH TIME ZONE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "CONSTRAINT mcp_oauth_tokens_tenant_principal_svc " +
                "UNIQUE (tenant_id, principal_type, principal_id, service_id))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS mcp_metadata (" +
                "tenant_id BIGINT NOT NULL, service_id VARCHAR(36) NOT NULL," +
                "principal VARCHAR(255) NOT NULL DEFAULT ''," +
                "config_fingerprint VARCHAR(64) NOT NULL, tools VARCHAR NOT NULL," +
                "instructions TEXT NOT NULL DEFAULT '', server_name TEXT NOT NULL DEFAULT ''," +
                "server_version TEXT NOT NULL DEFAULT '', server_description TEXT NOT NULL DEFAULT ''," +
                "synced_at TIMESTAMP WITH TIME ZONE NOT NULL," +
                "PRIMARY KEY (tenant_id, service_id, principal))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS mcp_tool_approvals (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL," +
                "service_id VARCHAR(36) NOT NULL, tool_name VARCHAR(512) NOT NULL," +
                "require_approval BOOLEAN NOT NULL DEFAULT FALSE," +
                "enabled BOOLEAN NOT NULL DEFAULT TRUE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "CONSTRAINT mcp_tool_approvals_tenant_svc_tool UNIQUE (tenant_id, service_id, tool_name))");
        // ── Wiki（列名/约束以迁移 000037/000061/000075 为准） ──
        // H2 用 VARCHAR 承载 jsonb（对照 PG 的 jsonb 列；读回由 TypeHandler 解析）。
        // jsonb 列在迁移里都是**可空**的（只有 DEFAULT，没有 NOT NULL），这里保持一致——
        // 否则"清空 page_metadata"的 UPDATE 会在 H2 上炸 NOT NULL，而 PG 上完全合法。
        // 索引：PG 的原始定义是
        //   CREATE UNIQUE INDEX idx_wiki_pages_kb_slug ON wiki_pages (knowledge_base_id, slug)
        //       WHERE deleted_at IS NULL;                                     -- 部分唯一索引
        //   CREATE UNIQUE INDEX idx_wiki_folders_parent_name
        //       ON wiki_folders (knowledge_base_id, parent_id, name) WHERE deleted_at IS NULL;
        //   CREATE INDEX idx_wiki_pages_fulltext ON wiki_pages USING GIN (to_tsvector(...)); -- PG 专有
        //   CREATE INDEX idx_wiki_pages_source_refs ON wiki_pages USING GIN (source_refs jsonb_path_ops);
        //   CREATE INDEX idx_wiki_pages_title_trgm ON wiki_pages USING GIN (lower(title) gin_trgm_ops);
        // H2 不支持部分索引 / GIN / jsonb_path_ops / gin_trgm_ops，**一律不建**：
        // 若改建成全量唯一索引会让"软删后重建同名 slug"直接冲突（比 PG 更严），
        // 反倒扭曲语义。唯一性在本仓库由 service 层保证。
        // 唯一在 H2 下等价的（非部分、普通 B-tree）索引是 wiki_page_revisions 的
        // (page_id, version) —— 它是 MERGE/ON CONFLICT 幂等写入的依赖，予以保留。
        jdbc.execute("CREATE TABLE IF NOT EXISTS wiki_pages (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL," +
                "knowledge_base_id VARCHAR(36) NOT NULL, slug VARCHAR(255) NOT NULL," +
                "title VARCHAR(512) NOT NULL DEFAULT '', page_type VARCHAR(32) NOT NULL DEFAULT 'summary'," +
                "status VARCHAR(32) NOT NULL DEFAULT 'published'," +
                "content TEXT NOT NULL DEFAULT '', summary TEXT NOT NULL DEFAULT ''," +
                "parent_slug VARCHAR(255) NOT NULL DEFAULT '', folder_id VARCHAR(36) NOT NULL DEFAULT ''," +
                "category_path VARCHAR DEFAULT '[]', wiki_path VARCHAR(1024) NOT NULL DEFAULT ''," +
                "depth INT NOT NULL DEFAULT 0, sort_order INT NOT NULL DEFAULT 0," +
                "source_refs VARCHAR DEFAULT '[]', chunk_refs VARCHAR DEFAULT '[]'," +
                "in_links VARCHAR DEFAULT '[]', out_links VARCHAR DEFAULT '[]'," +
                "page_metadata VARCHAR DEFAULT '{}', aliases VARCHAR DEFAULT '[]'," +
                "version INT NOT NULL DEFAULT 1," +
                "last_edit_source VARCHAR(16) NOT NULL DEFAULT ''," +
                "last_editor_id VARCHAR(64) NOT NULL DEFAULT ''," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS wiki_folders (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL DEFAULT 0," +
                "knowledge_base_id VARCHAR(36) NOT NULL, parent_id VARCHAR(36) NOT NULL DEFAULT ''," +
                "name VARCHAR(255) NOT NULL, path VARCHAR(1024) NOT NULL DEFAULT ''," +
                "depth INT NOT NULL DEFAULT 0, sort_order INT NOT NULL DEFAULT 0," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS wiki_page_revisions (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL," +
                "knowledge_base_id VARCHAR(36) NOT NULL, page_id VARCHAR(36) NOT NULL," +
                "slug VARCHAR(255) NOT NULL, version INT NOT NULL," +
                "title VARCHAR(512) NOT NULL DEFAULT '', page_type VARCHAR(32) NOT NULL DEFAULT 'summary'," +
                "status VARCHAR(32) NOT NULL DEFAULT 'published'," +
                "content TEXT NOT NULL DEFAULT '', summary TEXT NOT NULL DEFAULT ''," +
                "aliases VARCHAR DEFAULT '[]'," +
                "edit_source VARCHAR(16) NOT NULL DEFAULT '', editor_id VARCHAR(64) NOT NULL DEFAULT ''," +
                "edited_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");
        // 与迁移一致的全量唯一索引（H2 下等价）
        jdbc.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_wiki_page_revisions_page_version "
                + "ON wiki_page_revisions (page_id, version)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS wiki_page_issues (" +
                "id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT NOT NULL," +
                "knowledge_base_id VARCHAR(36) NOT NULL, slug VARCHAR(255) NOT NULL," +
                "issue_type VARCHAR(50) NOT NULL, description TEXT NOT NULL," +
                "suspected_knowledge_ids VARCHAR," +
                "status VARCHAR(20) NOT NULL DEFAULT 'pending', reported_by VARCHAR(100) NOT NULL," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        // ── 通用任务队列（列名/约束以迁移 000041 为准） ──
        // 这两张表是 wiki ingest 的持久化待办队列与死信档案
        // （task_pending_ops / task_dead_letters）。payload 在 PG 里是 jsonb、
        // 在 H2 里用 VARCHAR 承载（读回由 PgJsonTypeHandler 解析）；
        // claimed_at 可空（NULL = 未认领）。
        // 索引：PG 的 idx_task_pending_ops_scope / _tenant 与
        // idx_task_dead_letters_{scope,tenant,task_type} 都只影响性能、不影响语义，
        // H2 的内联索引语法与 PG 也不同，故一律不建（与 wiki_pages 的处理一致）。
        jdbc.execute("CREATE TABLE IF NOT EXISTS task_pending_ops (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "task_type VARCHAR(64) NOT NULL," +
                "scope VARCHAR(32) NOT NULL," +
                "scope_id VARCHAR(64) NOT NULL," +
                "op VARCHAR(32) NOT NULL," +
                "dedup_key VARCHAR(128) NOT NULL DEFAULT ''," +
                "payload VARCHAR NOT NULL DEFAULT '{}'," +
                "fail_count INT NOT NULL DEFAULT 0," +
                "enqueued_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "claimed_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS task_dead_letters (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "task_type VARCHAR(64) NOT NULL," +
                "scope VARCHAR(32) NOT NULL," +
                "scope_id VARCHAR(64) NOT NULL," +
                "related_id VARCHAR(64) NOT NULL DEFAULT ''," +
                "payload VARCHAR NOT NULL," +
                "last_error TEXT NOT NULL DEFAULT ''," +
                "fail_count INT NOT NULL," +
                "failed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");

        // ── 横切回补：租户 API Key（列名/约束以迁移 000065 + 000071 为准） ──
        // 两点必须与迁移一致：
        //   1. tenant_id **可空**（000071 平台级 Key 用 NULL + scope_type='platform'）；
        //   2. knowledge_base_ids / capabilities 是 JSONB **NOT NULL DEFAULT '[]'** ——
        //      空集合写入的是字面量 jsonb `null`（不是 SQL NULL），
        //      H2 用 VARCHAR 承载，写路径必须真的能表达这个区别；
        //      若这里去掉 NOT NULL，就再也测不出"写 SQL NULL 会被 PG 拒绝"这类错。
        // key_hash 的 UNIQUE 在 PG 是 000065 建的唯一索引，H2 用内联 UNIQUE 等价。
        jdbc.execute("CREATE TABLE IF NOT EXISTS tenant_api_keys (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "tenant_id BIGINT," +
                "scope_type VARCHAR(16) NOT NULL DEFAULT 'tenant'," +
                "name VARCHAR(128) NOT NULL," +
                "key_hash VARCHAR(64) NOT NULL UNIQUE," +
                "api_key VARCHAR NOT NULL DEFAULT ''," +
                "full_access BOOLEAN NOT NULL DEFAULT FALSE," +
                "knowledge_base_ids VARCHAR NOT NULL DEFAULT '[]'," +
                "capabilities VARCHAR NOT NULL DEFAULT '[]'," +
                "last_used_at TIMESTAMP WITH TIME ZONE," +
                "expires_at TIMESTAMP WITH TIME ZONE," +
                "revoked_at TIMESTAMP WITH TIME ZONE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");

        // ── 横切回补：审计日志（列名/约束以迁移 000044 + 000073 为准） ──
        // 两点必须与迁移一致：
        //   1. 只追加表——没有 updated_at、没有 deleted_at（无软删除、无 Update）；
        //   2. details JSONB **NOT NULL DEFAULT '{}'**：落库行为是 null 字段从
        //      INSERT 列清单里省略、由库默认填 '{}'；MyBatis-Plus 的默认 insertStrategy
        //      （NOT_NULL）正是这个语义。**不要**去掉 NOT NULL 或
        //      改成写 NULL（Wiki page_metadata 是另一种处置）。
        // scope_type/scope_id 由迁移 000073 补入，H2 这里直接内联全列。
        jdbc.execute("CREATE TABLE IF NOT EXISTS audit_logs (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "actor_user_id VARCHAR(36) NOT NULL DEFAULT ''," +
                "actor_role VARCHAR(32) NOT NULL DEFAULT ''," +
                "action VARCHAR(64) NOT NULL," +
                "scope_type VARCHAR(32) NOT NULL DEFAULT ''," +
                "scope_id VARCHAR(64) NOT NULL DEFAULT ''," +
                "target_type VARCHAR(32) NOT NULL DEFAULT ''," +
                "target_id VARCHAR(64) NOT NULL DEFAULT ''," +
                "target_user_id VARCHAR(36) NOT NULL DEFAULT ''," +
                "request_path VARCHAR(512) NOT NULL DEFAULT ''," +
                "request_method VARCHAR(16) NOT NULL DEFAULT ''," +
                "outcome VARCHAR(16) NOT NULL DEFAULT 'success'," +
                "details VARCHAR NOT NULL DEFAULT '{}'," +
                "created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)");

        // sessions：**只建实体映射到的那些列**。迁移 000001 建的一批策略配置列
        // （knowledge_base_id / max_rounds / enable_rewrite / … / summary_parameters）
        // Java 实体不映射、由 DB 默认值兜住。这里也不建——建了反而会掩盖
        // "Java 不该写这些列"这件事。真 PG 上那些列的 NOT NULL 由 DEFAULT 满足。
        jdbc.execute("CREATE TABLE IF NOT EXISTS sessions (" +
                "id VARCHAR(36) PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "title VARCHAR(255)," +
                "description TEXT," +
                "user_id VARCHAR(512)," +
                "is_pinned BOOLEAN NOT NULL DEFAULT FALSE," +
                "pinned_at TIMESTAMP WITH TIME ZONE," +
                "agent_config VARCHAR," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");

        // messages：消息模块。同样只建实体映射到的列——迁移 000001 的那些
        // 列在实体里都有对应字段，故这里与真库基本一致；jsonb 列在 H2 用 VARCHAR 承载。
        jdbc.execute("CREATE TABLE IF NOT EXISTS messages (" +
                "id VARCHAR(36) PRIMARY KEY," +
                "request_id VARCHAR(36) NOT NULL DEFAULT ''," +
                "session_id VARCHAR(36) NOT NULL," +
                "role VARCHAR(50) NOT NULL DEFAULT ''," +
                "content TEXT NOT NULL DEFAULT ''," +
                "knowledge_references VARCHAR NOT NULL DEFAULT '[]'," +
                "agent_steps VARCHAR," +
                "is_completed BOOLEAN NOT NULL DEFAULT FALSE," +
                "mentioned_items VARCHAR DEFAULT '[]'," +
                "is_fallback BOOLEAN DEFAULT FALSE," +
                "agent_duration_ms BIGINT DEFAULT 0," +
                "knowledge_id VARCHAR(36)," +
                "images VARCHAR DEFAULT '[]'," +
                "channel VARCHAR(50) NOT NULL DEFAULT ''," +
                "rendered_content TEXT NOT NULL DEFAULT ''," +
                "attachments VARCHAR DEFAULT '[]'," +
                "agent_id VARCHAR(36) NOT NULL DEFAULT ''," +
                "agent_tenant_id BIGINT NOT NULL DEFAULT 0," +
                "model_id VARCHAR(64) NOT NULL DEFAULT ''," +
                "execution_context VARCHAR NOT NULL DEFAULT '{}'," +
                "artifacts VARCHAR DEFAULT '[]'," +
                "used_memories VARCHAR," +
                "usage VARCHAR," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");

        // message_suggestion_sets：**唯一索引是语义的一部分**——AcquireGeneration 的
        // "插入或什么都不做"就靠 (tenant_id, assistant_message_id, placement, config_hash, locale)。
        jdbc.execute("CREATE TABLE IF NOT EXISTS message_suggestion_sets (" +
                "id VARCHAR(36) PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "session_id VARCHAR(36) NOT NULL," +
                "assistant_message_id VARCHAR(36) NOT NULL," +
                "agent_id VARCHAR(36) NOT NULL DEFAULT ''," +
                "agent_tenant_id BIGINT NOT NULL DEFAULT 0," +
                "placement VARCHAR(32) NOT NULL," +
                "config_hash VARCHAR(64) NOT NULL," +
                "locale VARCHAR(16) NOT NULL DEFAULT ''," +
                "status VARCHAR(16) NOT NULL," +
                "allow_regenerate BOOLEAN NOT NULL DEFAULT FALSE," +
                "suppression_reason VARCHAR(64) NOT NULL DEFAULT ''," +
                "questions VARCHAR NOT NULL DEFAULT '[]'," +
                "model_id VARCHAR(64) NOT NULL DEFAULT ''," +
                "prompt_tokens INT NOT NULL DEFAULT 0," +
                "completion_tokens INT NOT NULL DEFAULT 0," +
                "latency_ms BIGINT NOT NULL DEFAULT 0," +
                "error_code VARCHAR(64) NOT NULL DEFAULT ''," +
                "lease_until TIMESTAMP WITH TIME ZONE," +
                "generated_at TIMESTAMP WITH TIME ZONE," +
                "created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP," +
                "CONSTRAINT uk_suggestion_cache_key UNIQUE " +
                "(tenant_id, assistant_message_id, placement, config_hash, locale))");

        jdbc.execute("CREATE TABLE IF NOT EXISTS message_suggestion_events (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "session_id VARCHAR(36) NOT NULL," +
                "suggestion_set_id VARCHAR(36) NOT NULL," +
                "question_id VARCHAR(64) NOT NULL DEFAULT ''," +
                "event_type VARCHAR(32) NOT NULL," +
                "actor_id VARCHAR(512) NOT NULL DEFAULT ''," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");

        // temporary_documents：会话附件。jsonb 列在 H2 用 VARCHAR 承载；
        // 时间列在真库是 **TIMESTAMP WITHOUT TIME ZONE**（naive），H2 用 TIMESTAMP 对齐。
        jdbc.execute("CREATE TABLE IF NOT EXISTS temporary_documents (" +
                "id VARCHAR(36) PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "session_id VARCHAR(36) NOT NULL," +
                "resource_ref TEXT NOT NULL," +
                "file_name VARCHAR(1024) NOT NULL," +
                "file_type VARCHAR(32) NOT NULL," +
                "mime_type VARCHAR(255) NOT NULL DEFAULT ''," +
                "file_size BIGINT NOT NULL," +
                "status VARCHAR(16) NOT NULL DEFAULT 'uploaded'," +
                "content TEXT NOT NULL DEFAULT ''," +
                "chunks VARCHAR NOT NULL DEFAULT '[]'," +
                "image_refs VARCHAR NOT NULL DEFAULT '[]'," +
                "metadata VARCHAR NOT NULL DEFAULT '{}'," +
                "processing_options VARCHAR NOT NULL DEFAULT '{}'," +
                "token_count INT NOT NULL DEFAULT 0," +
                "chunk_count INT NOT NULL DEFAULT 0," +
                "error_message TEXT NOT NULL DEFAULT ''," +
                "expires_at TIMESTAMP NOT NULL," +
                "started_at TIMESTAMP," +
                "ready_at TIMESTAMP," +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP)");

        // im_channel_sessions：会话的来源/归属信息。IM 模块本身还没翻，
        // 但 sessions 的两条查询要用到它（GetIMPlatform 的 JOIN、QueryPaged 的 LEFT JOIN），
        // 所以先把表建出来。
        jdbc.execute("CREATE TABLE IF NOT EXISTS im_channel_sessions (" +
                "id VARCHAR(36) PRIMARY KEY," +
                "platform VARCHAR(20) NOT NULL," +
                "user_id VARCHAR(128) NOT NULL," +
                "chat_id VARCHAR(128) NOT NULL DEFAULT ''," +
                "session_id VARCHAR(36) NOT NULL," +
                "tenant_id BIGINT NOT NULL," +
                "agent_id VARCHAR(36) DEFAULT ''," +
                "status VARCHAR(20) NOT NULL DEFAULT 'active'," +
                "metadata VARCHAR DEFAULT '{}'," +
                "im_channel_id VARCHAR(36) DEFAULT ''," +
                "thread_id VARCHAR(128) NOT NULL DEFAULT ''," +
                "created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");

        // mcp_metadata 的工具计数走 json_array_length（PG 方言）；
        // wiki 的"有目录优先"排序走 jsonb_array_length（PG 方言）。
        // H2 两个函数都没有，这里各注册一个同名 ALIAS 指向本类的 Java 实现，
        // 让**同一条 SQL** 在测试库上也能跑。
        jdbc.execute("CREATE ALIAS IF NOT EXISTS json_array_length FOR "
                + "\"com.ragagent.TestSchema.jsonArrayLength\"");
        jdbc.execute("CREATE ALIAS IF NOT EXISTS jsonb_array_length FOR "
                + "\"com.ragagent.TestSchema.jsonArrayLength\"");

        createMemoryTables(jdbc);
        createDatasourceTables(jdbc);
        createInfraConfigTables(jdbc);
    }

    /**
     * 基础设施配置三组的两张新表（web_search_providers=迁移 000030、
     * vector_stores=迁移 000032，列序/默认值以迁移为准）+ resources /
     * resource_bindings / resource_access_grants（迁移 000069 资源注册表——
     * 全投影并补齐两张伴生表，/r/ 能力 URL 与 scoped 文件代理依赖它们）。
     * 两个 config jsonb 列在 PG 有 DEFAULT（'{}'）——实体恒持非 null 对象，不依赖默认。
     */
    private static void createInfraConfigTables(JdbcTemplate jdbc) {
        jdbc.execute("CREATE TABLE IF NOT EXISTS web_search_providers (" +
                "id VARCHAR(36) NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, " +
                "name VARCHAR(255) NOT NULL, provider VARCHAR(50) NOT NULL, description TEXT, " +
                "parameters VARCHAR, is_default BOOLEAN DEFAULT FALSE, " +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, " +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, " +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS vector_stores (" +
                "id VARCHAR(36) NOT NULL PRIMARY KEY, name VARCHAR(255) NOT NULL, " +
                "engine_type VARCHAR(50) NOT NULL, connection_config VARCHAR NOT NULL DEFAULT '{}', " +
                "index_config VARCHAR NOT NULL DEFAULT '{}', tenant_id BIGINT NOT NULL, " +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, " +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, " +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        // 资源注册表：按迁移 000069 补齐全投影。
        jdbc.execute("CREATE TABLE IF NOT EXISTS resources (" +
                "id VARCHAR(36) NOT NULL PRIMARY KEY, handle VARCHAR(22) NOT NULL, " +
                "tenant_id BIGINT NOT NULL, storage_backend_id VARCHAR(36), " +
                "provider VARCHAR(32) NOT NULL, physical_path TEXT NOT NULL, " +
                "location_hash VARCHAR(64) NOT NULL, " +
                "kind VARCHAR(32) NOT NULL DEFAULT 'file', " +
                "mime_type VARCHAR(255) NOT NULL DEFAULT '', " +
                "original_name VARCHAR(1024) NOT NULL DEFAULT '', " +
                "size BIGINT NOT NULL DEFAULT 0, " +
                "content_hash VARCHAR(64) NOT NULL DEFAULT '', " +
                "lifecycle VARCHAR(16) NOT NULL DEFAULT 'persistent', " +
                "expires_at TIMESTAMP WITH TIME ZONE, state VARCHAR(16) NOT NULL DEFAULT 'active', " +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, " +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, " +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        // 迁移 000069 的两张伴生表：绑定=存活声明、授权=/r/ 能力令牌行。
        // H2 不建 PG 的 UNIQUE INDEX 与 FK（同既有表纪律）。
        jdbc.execute("CREATE TABLE IF NOT EXISTS resource_bindings (" +
                "id VARCHAR(36) NOT NULL PRIMARY KEY, resource_id VARCHAR(36) NOT NULL, " +
                "tenant_id BIGINT NOT NULL, owner_type VARCHAR(32) NOT NULL, " +
                "owner_id VARCHAR(64) NOT NULL, relation VARCHAR(32) NOT NULL DEFAULT 'attachment', " +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS resource_access_grants (" +
                "id VARCHAR(36) NOT NULL PRIMARY KEY, token_hash VARCHAR(64) NOT NULL, " +
                "resource_id VARCHAR(36) NOT NULL, access_scope VARCHAR(16) NOT NULL DEFAULT 'read', " +
                "expires_at TIMESTAMP WITH TIME ZONE NOT NULL, revoked_at TIMESTAMP WITH TIME ZONE, " +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");
    }

    /**
     * datasource 模块的 2 张表（迁移
     * {@code 000029_datasource_tables.up.sql}）。
     *
     * <p><b>该迁移是这两张表的唯一来源</b>：全仓再没有第二个迁移碰过
     * {@code data_sources} / {@code sync_logs}（{@code 000076} 只给
     * {@code knowledges} 加了个表达式索引），所以**没有 {@code ALTER TABLE} 追加列要合并**。</p>
     *
     * <h2>与 PG DDL 的差异（都是 H2 限制，迁移一字不改）</h2>
     * <ul>
     *   <li>{@code JSONB} → {@code VARCHAR}（测试库统一用 VARCHAR 承载 jsonb，
     *       读回由 {@code PgJsonTypeHandler} 解析；同既有表）。</li>
     *   <li>PG 的 {@code TIMESTAMP}（不带时区）→ {@code TIMESTAMP WITH TIME ZONE}
     *       ——与 TestSchema 里所有既有表一致。真库那两列是 naive timestamp，
     *       但写入侧一律写完整时间戳、读回也只做排序用，语义一致。</li>
     *   <li>{@code sync_logs.data_source_id} 的
     *       {@code REFERENCES data_sources(id) ON DELETE CASCADE} 外键**不建**：
     *       其一，与既有表（memory 的七张、im_channel_sessions 等）的处理一致；
     *       其二，{@code data_sources} 是软删（{@code deleted_at}），
     *       cascade 在真库上永远不会触发，去掉它不改变任何可观察行为。</li>
     *   <li>五个普通索引（{@code idx_data_sources_*} / {@code idx_sync_logs_*}）
     *       不建——它们只影响性能。唯一影响语义的索引（唯一约束）本表没有。</li>
     * </ul>
     *
     * <p>⚠️ <b>没有 DEFAULT 的 jsonb 列</b>：迁移里 {@code config} /
     * {@code last_sync_cursor} / {@code last_sync_result} / {@code result}
     * 都**可空且无默认值**，所以 MyBatis-Plus 对 null 字段省略该列会落到 SQL NULL——
     * 这里保持迁移的"可空、无 default"，**不要**加上 {@code DEFAULT '{}'}
     * （那会让"写 NULL"与"写 {}"再也测不出差别）。</p>
     */
    private static void createDatasourceTables(JdbcTemplate jdbc) {
        jdbc.execute("CREATE TABLE IF NOT EXISTS data_sources (" +
                "id VARCHAR(36) NOT NULL PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "knowledge_base_id VARCHAR(36) NOT NULL," +
                "name VARCHAR(255) NOT NULL," +
                "type VARCHAR(50) NOT NULL," +
                "config VARCHAR," +
                "sync_schedule VARCHAR(100)," +
                "sync_mode VARCHAR(20) DEFAULT 'incremental'," +
                "status VARCHAR(32) DEFAULT 'active'," +
                "conflict_strategy VARCHAR(32) DEFAULT 'overwrite'," +
                "sync_deletions BOOLEAN DEFAULT TRUE," +
                "last_sync_at TIMESTAMP WITH TIME ZONE," +
                "last_sync_cursor VARCHAR," +
                "last_sync_result VARCHAR," +
                "error_message TEXT," +
                "sync_log_retention_days INT DEFAULT 30," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");

        jdbc.execute("CREATE TABLE IF NOT EXISTS sync_logs (" +
                "id VARCHAR(36) NOT NULL PRIMARY KEY," +
                "data_source_id VARCHAR(36) NOT NULL," +
                "tenant_id BIGINT NOT NULL," +
                "status VARCHAR(32) NOT NULL," +
                "started_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "finished_at TIMESTAMP WITH TIME ZONE," +
                "items_total INT DEFAULT 0," +
                "items_created INT DEFAULT 0," +
                "items_updated INT DEFAULT 0," +
                "items_deleted INT DEFAULT 0," +
                "items_skipped INT DEFAULT 0," +
                "items_failed INT DEFAULT 0," +
                "error_message TEXT," +
                "result VARCHAR," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");
    }

    /**
     * memory 模块的 7 张表（迁移 {@code 000084_memory} + {@code 000094_memory_consistency}
     * + {@code 000095_memory_vector_search}）。
     *
     * <p>三处与 PG 的 DDL 有意的差异，都是 H2 的限制（**迁移一字不改，索引以迁移为准**）：</p>
     * <ul>
     *   <li>{@code JSONB} → {@code VARCHAR}（测试库统一用 VARCHAR 承载 jsonb，同既有表）；</li>
     *   <li>PG 的 {@code uuid_generate_v4()} 默认值去掉——H2 没有该函数，
     *       而 id 一律由应用层生成（同既有表）；</li>
     *   <li>{@code memory_item_embeddings.embedding}（pgvector 的 {@code halfvec}）
     *       → {@code VARBINARY}。向量列只在 PG 上真正使用，测试库只需列存在能落盘。</li>
     * </ul>
     *
     * <p>注意 {@code memory_extraction_sessions} 是**复合主键**
     * （{@code (tenant_id, subject_id, session_id)}），没有 id 列。</p>
     */
    private static void createMemoryTables(JdbcTemplate jdbc) {
        // memory_subjects：一个主体在一个工作区里的记忆空间。
        // extraction_state / consolidated_at / forced_consolidated_at 由 000094 追加。
        jdbc.execute("CREATE TABLE IF NOT EXISTS memory_subjects (" +
                "id VARCHAR(36) PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "subject_id VARCHAR(512) NOT NULL," +
                "enabled BOOLEAN NOT NULL DEFAULT TRUE," +
                "block_text VARCHAR NOT NULL DEFAULT ''," +
                "block_updated_at TIMESTAMP WITH TIME ZONE," +
                "item_count INTEGER NOT NULL DEFAULT 0," +
                "last_extracted_at TIMESTAMP WITH TIME ZONE," +
                "extract_cursor TIMESTAMP WITH TIME ZONE," +
                "extraction_state VARCHAR," +
                "pending_sessions VARCHAR," +
                "extract_scheduled_at TIMESTAMP WITH TIME ZONE," +
                "consolidated_at TIMESTAMP WITH TIME ZONE," +
                "forced_consolidated_at TIMESTAMP WITH TIME ZONE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_memory_subjects_scope " +
                "ON memory_subjects (tenant_id, subject_id)");

        // memory_items：一条被记住的陈述。replaces_id 由 000094 追加。
        jdbc.execute("CREATE TABLE IF NOT EXISTS memory_items (" +
                "id VARCHAR(36) PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "subject_id VARCHAR(512) NOT NULL," +
                "kind VARCHAR(32) NOT NULL," +
                "content VARCHAR NOT NULL," +
                "topic VARCHAR(255) NOT NULL DEFAULT ''," +
                "normalized_key VARCHAR(255) NOT NULL DEFAULT ''," +
                "importance SMALLINT NOT NULL DEFAULT 3," +
                "origin VARCHAR(16) NOT NULL DEFAULT 'extracted'," +
                "status VARCHAR(16) NOT NULL DEFAULT 'active'," +
                "source_session_id VARCHAR(36)," +
                "source_message_id VARCHAR(36)," +
                "valid_from TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP," +
                "invalid_at TIMESTAMP WITH TIME ZONE," +
                "expires_at TIMESTAMP WITH TIME ZONE," +
                "replaces_id VARCHAR(36) NOT NULL DEFAULT ''," +
                "superseded_by VARCHAR(36)," +
                "last_used_at TIMESTAMP WITH TIME ZONE," +
                "use_count INTEGER NOT NULL DEFAULT 0," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE INDEX IF NOT EXISTS idx_memory_items_scope " +
                "ON memory_items (tenant_id, subject_id, status)");
        jdbc.execute("CREATE INDEX IF NOT EXISTS idx_memory_items_key " +
                "ON memory_items (tenant_id, subject_id, normalized_key)");
        jdbc.execute("CREATE INDEX IF NOT EXISTS idx_memory_replaces " +
                "ON memory_items (tenant_id, subject_id, replaces_id, status)");

        // memory_tombstones：记"这条被刻意忘掉了"，免得后台蒸馏又把它加回来。
        jdbc.execute("CREATE TABLE IF NOT EXISTS memory_tombstones (" +
                "id VARCHAR(36) PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "subject_id VARCHAR(512) NOT NULL," +
                "topic VARCHAR(255) NOT NULL DEFAULT ''," +
                "fingerprint VARCHAR(64) NOT NULL," +
                "source_message_id VARCHAR(36)," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_mem_tomb_fp " +
                "ON memory_tombstones (tenant_id, subject_id, fingerprint)");
        jdbc.execute("CREATE INDEX IF NOT EXISTS idx_memory_tombstones_scope " +
                "ON memory_tombstones (tenant_id, subject_id)");

        // memory_topic_stats：aliases 由 000094 追加（NOT NULL DEFAULT '[]'）。
        jdbc.execute("CREATE TABLE IF NOT EXISTS memory_topic_stats (" +
                "id VARCHAR(36) PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "subject_id VARCHAR(512) NOT NULL," +
                "normalized_key VARCHAR(255) NOT NULL," +
                "topic VARCHAR(255) NOT NULL DEFAULT ''," +
                "aliases VARCHAR NOT NULL DEFAULT '[]'," +
                "hits INTEGER NOT NULL DEFAULT 0," +
                "last_seen_at TIMESTAMP WITH TIME ZONE," +
                "promoted_at TIMESTAMP WITH TIME ZONE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_mem_topic_scope " +
                "ON memory_topic_stats (tenant_id, subject_id, normalized_key)");

        // memory_doc_affinity：这个人的回答反复取材于哪些文档。
        jdbc.execute("CREATE TABLE IF NOT EXISTS memory_doc_affinity (" +
                "id VARCHAR(36) PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "subject_id VARCHAR(512) NOT NULL," +
                "knowledge_id VARCHAR(36) NOT NULL," +
                "knowledge_base_id VARCHAR(36) NOT NULL DEFAULT ''," +
                "title VARCHAR(512) NOT NULL DEFAULT ''," +
                "hits INTEGER NOT NULL DEFAULT 0," +
                "last_used_at TIMESTAMP WITH TIME ZONE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_mem_affinity_scope " +
                "ON memory_doc_affinity (tenant_id, subject_id, knowledge_id)");

        // memory_item_embeddings：PG 上是 pgvector 的 halfvec（000095）。
        jdbc.execute("CREATE TABLE IF NOT EXISTS memory_item_embeddings (" +
                "item_id VARCHAR(36) PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "subject_id VARCHAR(512) NOT NULL," +
                "model_id VARCHAR(64) NOT NULL DEFAULT ''," +
                "dims INTEGER NOT NULL DEFAULT 0," +
                "vector VARBINARY," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE INDEX IF NOT EXISTS idx_mem_emb_scope " +
                "ON memory_item_embeddings (tenant_id, subject_id)");

        // memory_extraction_sessions：每个会话自己的蒸馏进度（复合主键，无 id 列）。
        jdbc.execute("CREATE TABLE IF NOT EXISTS memory_extraction_sessions (" +
                "tenant_id BIGINT NOT NULL," +
                "subject_id VARCHAR(512) NOT NULL," +
                "session_id VARCHAR(36) NOT NULL," +
                "revision BIGINT NOT NULL DEFAULT 0," +
                "cursor_at TIMESTAMP WITH TIME ZONE," +
                "cursor_id VARCHAR(36) NOT NULL DEFAULT ''," +
                "pending BOOLEAN NOT NULL DEFAULT FALSE," +
                "failure_count INTEGER NOT NULL DEFAULT 0," +
                "failure_code VARCHAR(64) NOT NULL DEFAULT ''," +
                "failed_from_at TIMESTAMP WITH TIME ZONE," +
                "failed_from_id VARCHAR(36) NOT NULL DEFAULT ''," +
                "failed_to_at TIMESTAMP WITH TIME ZONE," +
                "failed_to_id VARCHAR(36) NOT NULL DEFAULT ''," +
                "failed_at TIMESTAMP WITH TIME ZONE," +
                "updated_at TIMESTAMP WITH TIME ZONE NOT NULL," +
                "PRIMARY KEY (tenant_id, subject_id, session_id))");
        jdbc.execute("CREATE INDEX IF NOT EXISTS idx_memory_extraction_pending " +
                "ON memory_extraction_sessions (tenant_id, subject_id, pending, updated_at, session_id)");
        // 系统设置（迁移 000053；平台级，非租户作用域）。
        // users.is_system_admin 列在 users 表定义里已有。
        // key/value 是 H2 保留字 → 建表带引号（MP 侧实体 @TableField 同步带引号）。
        jdbc.execute("CREATE TABLE IF NOT EXISTS system_settings (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "\"key\" VARCHAR(128) NOT NULL UNIQUE," +
                "\"value\" VARCHAR NOT NULL," +
                "value_type VARCHAR(16) NOT NULL," +
                "category VARCHAR(32) NOT NULL," +
                "description VARCHAR NOT NULL DEFAULT ''," +
                "is_secret BOOLEAN NOT NULL DEFAULT FALSE," +
                "requires_restart BOOLEAN NOT NULL DEFAULT FALSE," +
                "last_modified_by VARCHAR(36) NOT NULL DEFAULT ''," +
                "created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)");
        // 用户收藏（迁移 000047）。
        // 复合主键、无外键（收藏在分享撤销/软删窗口内保留）；resource_type 'kb'|'agent'。
        jdbc.execute("CREATE TABLE IF NOT EXISTS user_resource_favorites (" +
                "user_id VARCHAR(36) NOT NULL," +
                "tenant_id BIGINT NOT NULL," +
                "resource_type VARCHAR(16) NOT NULL," +
                "resource_id VARCHAR(64) NOT NULL," +
                "created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP," +
                "PRIMARY KEY (user_id, tenant_id, resource_type, resource_id))");
        // embed_channels（迁移 000060 全列；allow_memory 列无实体字段映射，不建）
        jdbc.execute("CREATE TABLE IF NOT EXISTS embed_channels (" +
                "id VARCHAR(36) PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "agent_id VARCHAR(36) NOT NULL DEFAULT 'builtin-quick-answer'," +
                "name VARCHAR(255) NOT NULL DEFAULT ''," +
                "enabled BOOLEAN NOT NULL DEFAULT TRUE," +
                "publish_token VARCHAR(64) NOT NULL DEFAULT ''," +
                "allowed_origins VARCHAR NOT NULL DEFAULT '[]'," +
                "welcome_message VARCHAR NOT NULL DEFAULT ''," +
                "rate_limit_per_minute INTEGER NOT NULL DEFAULT 30," +
                "rate_limit_per_day INTEGER NOT NULL DEFAULT 10000," +
                "primary_color VARCHAR(32) NOT NULL DEFAULT ''," +
                "page_title VARCHAR(255) NOT NULL DEFAULT ''," +
                "header_title_mode VARCHAR(32) NOT NULL DEFAULT 'channel'," +
                "show_suggested_questions BOOLEAN NOT NULL DEFAULT TRUE," +
                "show_thinking BOOLEAN NOT NULL DEFAULT FALSE," +
                "widget_position VARCHAR(32) NOT NULL DEFAULT 'bottom-right'," +
                "allow_web_search BOOLEAN NOT NULL DEFAULT FALSE," +
                "allow_file_upload BOOLEAN NOT NULL DEFAULT FALSE," +
                "default_locale VARCHAR(16) NOT NULL DEFAULT ''," +
                "webhook_url VARCHAR(512) NOT NULL DEFAULT ''," +
                "webhook_secret VARCHAR(128) NOT NULL DEFAULT ''," +
                "launcher_icon VARCHAR NOT NULL DEFAULT ''," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        // im_channels（迁移 000021 + 000023 kb_id + 000024 bot_identity + 000028 session_mode）
        jdbc.execute("CREATE TABLE IF NOT EXISTS im_channels (" +
                "id VARCHAR(36) PRIMARY KEY," +
                "tenant_id BIGINT NOT NULL," +
                "agent_id VARCHAR(36) NOT NULL," +
                "platform VARCHAR(20) NOT NULL," +
                "name VARCHAR(255) NOT NULL DEFAULT ''," +
                "enabled BOOLEAN NOT NULL DEFAULT TRUE," +
                "mode VARCHAR(20) NOT NULL DEFAULT 'websocket'," +
                "output_mode VARCHAR(20) NOT NULL DEFAULT 'stream'," +
                "knowledge_base_id VARCHAR(36) DEFAULT ''," +
                "bot_identity VARCHAR(255) NOT NULL DEFAULT ''," +
                "session_mode VARCHAR(20) NOT NULL DEFAULT 'user'," +
                "credentials VARCHAR NOT NULL DEFAULT '{}'," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
    }

    /**
     * H2 ALIAS 目标：对照 PG {@code json_array_length(json)}。
     * 入参是 H2 的 VARCHAR（测试库用 VARCHAR 承载 jsonb），内容必须是 JSON 数组。
     */
    public static int jsonArrayLength(String json) {
        if (json == null || json.isEmpty()) {
            return 0;
        }
        try {
            com.fasterxml.jackson.databind.JsonNode node =
                    new com.fasterxml.jackson.databind.ObjectMapper().readTree(json);
            return node.isArray() ? node.size() : 0;
        } catch (Exception e) {
            throw new IllegalArgumentException("json_array_length: invalid JSON", e);
        }
    }

    /** 清空全部数据（外键无依赖，任意顺序） */
    public static void resetData(JdbcTemplate jdbc) {
        jdbc.execute("DELETE FROM auth_tokens");
        jdbc.execute("DELETE FROM tenant_members");
        // 邀请行（members 之前删，外键序无实际约束但保持惯例）
        jdbc.execute("DELETE FROM tenant_invitations");
        jdbc.execute("DELETE FROM users");
        jdbc.execute("DELETE FROM tenants");
        jdbc.execute("DELETE FROM models");
        jdbc.execute("DELETE FROM knowledge_bases");
        jdbc.execute("DELETE FROM knowledges");
        jdbc.execute("DELETE FROM chunks");
        jdbc.execute("DELETE FROM chunk_revisions");
        jdbc.execute("DELETE FROM knowledge_tag_relations");
        jdbc.execute("DELETE FROM knowledge_tags");
        jdbc.execute("DELETE FROM user_kb_pins");
        jdbc.execute("DELETE FROM storage_backends");
        jdbc.execute("DELETE FROM embeddings");
        jdbc.execute("DELETE FROM knowledge_processing_spans");
        jdbc.execute("DELETE FROM custom_agents");
        jdbc.execute("DELETE FROM mcp_tool_approvals");
        jdbc.execute("DELETE FROM mcp_metadata");
        jdbc.execute("DELETE FROM mcp_oauth_tokens");
        jdbc.execute("DELETE FROM mcp_oauth_clients");
        jdbc.execute("DELETE FROM mcp_services");
        jdbc.execute("DELETE FROM wiki_page_issues");
        jdbc.execute("DELETE FROM wiki_page_revisions");
        jdbc.execute("DELETE FROM wiki_pages");
        jdbc.execute("DELETE FROM wiki_folders");
        jdbc.execute("DELETE FROM task_pending_ops");
        jdbc.execute("DELETE FROM task_dead_letters");
        jdbc.execute("DELETE FROM tenant_api_keys");
        jdbc.execute("DELETE FROM audit_logs");
        // 子表先删（im_channel_sessions 有指向 sessions 的外键；messages 逻辑上也是子表）
        jdbc.execute("DELETE FROM message_suggestion_events");
        jdbc.execute("DELETE FROM message_suggestion_sets");
        jdbc.execute("DELETE FROM temporary_documents");
        jdbc.execute("DELETE FROM messages");
        jdbc.execute("DELETE FROM im_channel_sessions");
        jdbc.execute("DELETE FROM sessions");
        // datasource：先子后父（真库里有 ON DELETE CASCADE，测试库没建外键，顺序照旧）
        jdbc.execute("DELETE FROM sync_logs");
        jdbc.execute("DELETE FROM data_sources");
        // 基础设施配置三组
        jdbc.execute("DELETE FROM web_search_providers");
        jdbc.execute("DELETE FROM vector_stores");
        jdbc.execute("DELETE FROM resources");
        // 资源注册表伴生表
        jdbc.execute("DELETE FROM resource_bindings");
        jdbc.execute("DELETE FROM resource_access_grants");
        // 系统设置
        jdbc.execute("DELETE FROM system_settings");
        // 用户收藏
        jdbc.execute("DELETE FROM user_resource_favorites");
        // embed 管理面 + im channels 清单面
        jdbc.execute("DELETE FROM im_channels");
        jdbc.execute("DELETE FROM embed_channels");
    }

    }
