package com.ragagent;

import org.springframework.jdbc.core.JdbcTemplate;

/**
 * 契约测试共享的 H2 schema（阶段 1+2 并集）。
 *
 * 所有契约测试必须用同一份 DDL：H2 内存库在 JVM 生命周期内共享
 * （DB_CLOSE_DELAY=-1），CREATE TABLE IF NOT EXISTS 不会补列，
 * 表结构以第一个执行的测试类为准——分叉的 DDL 会让后跑的类炸列错误。
 * 新增模块时在此追加表定义，禁止在测试类里私建同名表。
 */
public final class TestSchema {

    private TestSchema() {}

    public static void createTables(JdbcTemplate jdbc) {
        jdbc.execute("CREATE TABLE IF NOT EXISTS users (" +
                "id VARCHAR(36) PRIMARY KEY, username VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL," +
                "password_hash VARCHAR(255) NOT NULL, avatar VARCHAR(500), tenant_id BIGINT," +
                "is_active BOOLEAN NOT NULL DEFAULT TRUE, can_access_all_tenants BOOLEAN NOT NULL DEFAULT FALSE," +
                "is_system_admin BOOLEAN NOT NULL DEFAULT FALSE, preferences VARCHAR NOT NULL DEFAULT '{}'," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS tenants (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "name VARCHAR NOT NULL, description VARCHAR NOT NULL DEFAULT '', status VARCHAR NOT NULL DEFAULT 'active'," +
                "retriever_engines VARCHAR NOT NULL DEFAULT '[]', business VARCHAR NOT NULL DEFAULT ''," +
                "storage_quota BIGINT NOT NULL DEFAULT 10737418240, storage_used BIGINT NOT NULL DEFAULT 0," +
                "context_config VARCHAR, web_search_config VARCHAR, parser_engine_config VARCHAR, credentials VARCHAR," +
                "storage_engine_config VARCHAR, default_storage_backend_id VARCHAR(36)," +
                "chat_history_config VARCHAR, retrieval_config VARCHAR, memory_config VARCHAR," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS tenant_members (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "user_id VARCHAR(36) NOT NULL, tenant_id BIGINT NOT NULL," +
                "role VARCHAR(20) NOT NULL DEFAULT 'contributor', status VARCHAR(20) NOT NULL DEFAULT 'active'," +
                "invited_by VARCHAR(36), joined_at TIMESTAMP WITH TIME ZONE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS auth_tokens (" +
                "id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL, token TEXT NOT NULL," +
                "token_type VARCHAR(50) NOT NULL, expires_at TIMESTAMP WITH TIME ZONE NOT NULL," +
                "is_revoked BOOLEAN NOT NULL DEFAULT FALSE," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS models (" +
                "id VARCHAR(64) PRIMARY KEY, tenant_id BIGINT NOT NULL, name VARCHAR(255) NOT NULL," +
                "display_name VARCHAR(255) NOT NULL DEFAULT '', type VARCHAR(50) NOT NULL, source VARCHAR(50) NOT NULL," +
                "description TEXT, parameters VARCHAR NOT NULL, is_default BOOLEAN NOT NULL DEFAULT FALSE," +
                "is_builtin BOOLEAN NOT NULL DEFAULT FALSE, managed_by VARCHAR(32) NOT NULL DEFAULT ''," +
                "status VARCHAR(50) NOT NULL DEFAULT 'active'," +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        // usage 查询依赖（knowledge_bases/custom_agents 仅阶段 2 引用计算所需列）
        jdbc.execute("CREATE TABLE IF NOT EXISTS knowledge_bases (" +
                "id VARCHAR(36) PRIMARY KEY, name VARCHAR NOT NULL, tenant_id BIGINT NOT NULL," +
                "embedding_model_id VARCHAR(64), summary_model_id VARCHAR(64)," +
                "image_processing_config VARCHAR, vlm_config VARCHAR, asr_config VARCHAR, wiki_config VARCHAR," +
                "deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS custom_agents (" +
                "id VARCHAR(36) PRIMARY KEY, name VARCHAR NOT NULL, tenant_id BIGINT NOT NULL," +
                "config VARCHAR, deleted_at TIMESTAMP WITH TIME ZONE)");
    }

    /** 清空全部数据（外键无依赖，任意顺序） */
    public static void resetData(JdbcTemplate jdbc) {
        jdbc.execute("DELETE FROM auth_tokens");
        jdbc.execute("DELETE FROM tenant_members");
        jdbc.execute("DELETE FROM users");
        jdbc.execute("DELETE FROM tenants");
        jdbc.execute("DELETE FROM models");
        jdbc.execute("DELETE FROM knowledge_bases");
        jdbc.execute("DELETE FROM custom_agents");
    }
}
